### ISSUE TITLE
Exception when trying to add to a document

### ISSUE THREAD

**Issue by francescovallone** [atn832/cloud_firestore_mocks#136]
Hello,
I'm trying to mock a wallet for a personal finance app. I need to pass it to the homepage but when I start the tests it throws:
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════

The following ArgumentError was thrown running a test:
Invalid argument: _LinkedHashMap len:4

When the exception was thrown, this was the stack:
#0      validateDocumentValue (package:cloud_firestore_mocks/src/util.dart:95:3)
#1      validateDocumentValue (package:cloud_firestore_mocks/src/util.dart:86:7)
#2      validateDocumentValue (package:cloud_firestore_mocks/src/util.dart:91:7)
#3      MockDocumentReference.update (package:cloud_firestore_mocks/src/mock_document_reference.dart:73:5)
#4      MockCollectionReference.add (package:cloud_firestore_mocks/src/mock_collection_reference.dart:162:29)
#5      main.<anonymous closure> (file:///C:/Users/icaru/Documents/Folder/test/pages/homepage_test.dart:30:44)
<asynchronous suspension>
#6      main.<anonymous closure> (file:///C:/Users/icaru/Documents/Folder/test/pages/homepage_test.dart)
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:146:29)
<asynchronous suspension>
#8      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#9      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:784:19)
<asynchronous suspension>
#12     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
#13     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1173:24)
#14     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:178:54)
#19     withClock (package:clock/src/default.dart:48:10)
#20     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:178:22)
#25     FakeAsync.run (package:fake_async/fake_async.dart:178:7)
#26     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1170:15)
#27     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
#28     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
<asynchronous suspension>
#29     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#34     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
#35     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
#40     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
#41     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
<asynchronous suspension>
#42     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#47     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
#48     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
#49     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
#56     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
#57     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#58     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:256:16)
#63     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:255:5)
#64     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:208:7)
#82     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#83     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#87     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#121    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#129    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#130    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#140    _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
#149    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#150    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
(elided 111 frames from dart:async and package:stack_trace)
```

And this is my test code:
```dart
void main() {
  testWidgets("Home Page", (WidgetTester tester) async{
      MockFirebaseAuth auth = MockFirebaseAuth();
      UserCredential userc = await auth.signInWithEmailAndPassword(email: "test@example.com", password: "123456");
      MockFirestoreInstance instance = MockFirestoreInstance();
      List<Map> m = [
        {
          "amount": 10,
          "category": "rent",
          "name": "Test",
          "date": FieldValue.serverTimestamp(),
        }
      ];
     // The error seems to be here
      await instance.collection("wallets").add({
        'uid': userc.user.uid,
        'movements': m
      });
      await tester.pumpWidget(testPage(Scaffold(body: HomePage(auth, instance))));
      await tester.idle();
      await tester.pump();
      expect(find.text("Test"), findsOneWidget);
    });
}
```

**Comment by AntoliniMatteo** [comment]
@francescovallone How did you solve it?
