### ISSUE TITLE
Error: Class 'FieldValue' has no instance getter '_delegate' with cloud_firestore: 0.13.4

### ISSUE THREAD

**Issue by suztomo** [atn832/cloud_firestore_mocks#68]
When I upgraded cloud_firestore: 0.13.4 in my project, one of the existing tests throws the following error:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following NoSuchMethodError was thrown running a test:
Class 'FieldValue' has no instance getter '_delegate'.
Receiver: Instance of 'FieldValue'
Tried calling: _delegate

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      FieldValuePlatform.getDelegate (package:cloud_firestore_platform_interface/src/platform_interface/field_value.dart:19:18)
#2      MockDocumentReference.updateData.<anonymous closure> (package:cloud_firestore_mocks/src/mock_document_reference.dart:57:50)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#4      MockDocumentReference.updateData (package:cloud_firestore_mocks/src/mock_document_reference.dart:49:10)
#5      _DummyTransaction.update (package:cloud_firestore_mocks/src/cloud_firestore_mocks_base.dart:158:30)
#6      TagsModel.save.<anonymous closure> (package:hitomemo/person_tags_model.dart:185:18)
<asynchronous suspension>
#7      MockFirestoreInstance.runTransaction (package:cloud_firestore_mocks/src/cloud_firestore_mocks_base.dart:63:51)
#8      TagsModel.save (package:hitomemo/person_tags_model.dart:173:39)
#9      main.<anonymous closure> (file:///Users/suztomo/Documents/hitomemo/test/tags_model_test.dart:56:30)
<asynchronous suspension>
...
```

**Comment by suztomo** [comment]
The problem does not occur if I use the master HEAD.

```
-  cloud_firestore_mocks: 0.4.2
+  cloud_firestore_mocks:
+    path: ../cloud_firestore_mocks
```
